import Head from 'next/head'
import Header from '../components/header/header'
import Product from '../components/product/product'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Product Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Product/>
    </div>
  )
}
