import Head from 'next/head'
import Header from '../components/header/header'
import Product from '../components/product/product'
import SimpleReactLightbox from 'simple-react-lightbox'
import { useState } from 'react'
export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Product Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@400;700&display=swap" rel="stylesheet"/>

      </Head>
      <Header/>
      <SimpleReactLightbox>
      <Product/>
      </SimpleReactLightbox>
    </div>
  )
}
